# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "\"Life on the Film Set\" Podcast"
email: listen@lifeonthefilmset.com
description: > # this means to ignore newlines until "baseurl:"
  A podcast about how to work on a film set and be great at it.
baseurl: 
url: 'https://www.lifeonthefilmset.com' # the base hostname & protocol for your site, e.g. http://example.com
repository: 'nbpayne/lifeonthefilmset'
locale: en_AU
formid: 

podcast:
  author: lifeonthefilmset
  logo: img/logo.jpg
  category: TV &amp; Film
  explicit: false
  type: episodic
  countryOfOrigin: au

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo
  - jekyll-sitemap
exclude:
  - bower_components
  - bower.json
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - node_modules
  - package.json
  - README.md
  - yarn.lock
permalink: /:year/:month/:day/:slug
defaults:
  -
    scope:
      path:            "docs/**/*.*"
    values:
      sitemap:         false
