- name: Nick Payne
  description: |
    From shooting silent Super 8 in high school through to Super VHS in the 90’s film was always 
    rooted in Nick's brain. Eventually it disturbed him so much that he quit his corporate job and
    started working on film sets.
    
    In doing so he realised that the stuff he used to teach about in his old world --- namely 
    leadership, project management, and team building --- was super relevant to how film sets are
    organised and optimised for greatness. With not much bugging from George he decided to make this
    podcast to help and inspire others.
  instagram: nickpayneandthe
- name: George Artin
  description: |
    He used to be a mechanic before running a coffee shop. He's now the world's funnest Assistant
    Camera-person. George embodies our values and always goes out of his way to help and teach 
    others on set.
    
    George brings a wealth of real-world experience and stories about how to be great when working 
    on a film set.
  instagram: dreamfilmsau
- name: The rest of the team
  description: |
    We've been blessed with an amazing team giving their time to help make this podcast a reality.
    
    So our heartfelt thanks goes out to...
    - **Ian Tamawidjaja** our cinematographer making us look great ([@ian.tama_dp](https://www.instagram.com/ian.tama_dp/){: target="_blank" })
    - **Ella Richards** our assistant camera-person ([@ellastone.dop](https://www.instagram.com/ellastone.dop/){: target="_blank" })
    - **David Do** our sound recordist ([@davidsbizarreaudio](https://www.instagram.com/davidsbizarreaudio/){: target="_blank" })
    - **Joe Hopkins** our graphic designer ([@joehootly](https://www.instagram.com/joehootly/){: target="_blank" })
    - **Jolin Jiang** for composing our theme music ([@jolinjiangmusic](https://www.instagram.com/jolinjiangmusic/){: target="_blank" })
